### PR TITLE
fix: (re)move breaks in links and headings

### LINKED ISSUE #106: improve linefeeds / whitespace handling inside links
```
└─1 paragraph[2]
    ├─0 link[3]
    │   │ url: "https://main--healthy-kp--hlxsites.hlx.page/northern-california/health-wellness/cancer-care/"
    │   ├─0 text "Cancer Care"
    │   ├─1 break "\n"
    │   └─2 break "\n"
```

- should move `break`s after `link`. 
- non leading/trailing `breaks` should be converted to spaces, as they can't be represented in markdown.

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #106

- moves leading _line breaks_ before link
- moves trailing _line breaks_ after link
- replaces _line breaks_ inside link with `<br>`.
- replaces _line breaks_ inside headings with `<br>`.

### CODE REVIEW

File: src/mdast-sanitize-links.js [hunk 1]
```diff
@@ -60,6 +62,31 @@ export default function sanitizeLinks(tree) {
...
       }
+    } else if (node.type === 'link' && children.length > 1) {
+      // move leading breaks outside of link
+      while (children[0]?.type === 'break') {
+        const brk = children.shift();
+        parent.children.splice(index, 0, brk);
+        // eslint-disable-next-line no-param-reassign
+        index += 1;
+      }
+      // move trailing links after link
```
Comment (rofe) [inline src/mdast-sanitize-links.js:73]:
```suggestion
      // move trailing breaks after link
```
?

**Review by rofe — APPROVED** [review]

**Review by rofe — APPROVED** [review]
